name: Run test

on:
  pull_request:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Update auth secrets
        env:
          AUTH_SECRET_IV: ${{ secrets.AUTH_SECRET_IV }}
          AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
        run: |
          cat <<EOF > local.properties
          AUTH_SECRET_IV:"$AUTH_SECRET_IV"
          AUTH_SECRET_KEY:"$AUTH_SECRET_KEY"
          EOF

      - name: Create BuildKonfig
        run: ./gradlew generateBuildKonfig

      - name: Build app
        run: ./gradlew assembleDebug assembleAndroidTest

      - name: Run Unit Tests
        run: |
          ./gradlew :core:common:test

#      - name: Run Android tests on Firebase Test Lab
#        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
#        with:
#          arg-spec: 'android-device.yml:android-pixel-4'
#        env:
#          SERVICE_ACCOUNT: ${{ secrets.FIREBASE_TEST_LAB_SERVICE_ACCOUNT }}

      - name: Publish test report
        uses: mikepenz/action-junit-report@v4.3.1
        if: always() # always run even if the tests fail
        with:
          report_paths: 'composeApp/build/test-results/**/*.xml'